### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bouarichaKarim** [MTH35H4RK/alx-system_engineering-devops#1]
6-multiple_permissions : the file hello has already some permissions and u have to **add** permissions. 
7-everybody

see my github bellow.

https://github.com/bouarichaKarim/alx-system_engineering-devops/tree/master/0x01-shell_permissions

**Comment by MTH35H4RK** [comment]
thanks, I corrected my mistakes

**Comment by bouarichaKarim** [comment]
with pleasure
